[tools]
deno = "2.5.6"
node = "lts"
ruby = "latest"
bun = "latest"
zig = "latest"
fnox = "latest"
redis = "latest"
uv = "latest"
python = "3.14"
rust = "1.91.1"
"pipx:ansible" = "13"
zola = "0.21"
awscli = "latest"
